---
version: "2.1"
services:
  putioarr:
    image: ghcr.io/wouterdebie/putioarr:main
    container_name: putioarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - UMASK=002
      volumes:
        - /home/monxas/appdata/putioarr:/config
        - /mnt/nfs_media/downloads:/downloads
      ports:
        - "9091:9091"
      restart: unless-stopped
      logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "8"
